name: 'cherrypicker'
description: 'cherry picks commits from one repository to another'
inputs:
  source-repository:
    description: 'The source repository from which to cherry pick. Ex: myOrg/my-source-repo'
    required: true
  commit-sha:
    description: 'The commit sha to cherry pick. Ex: abcdef0123456789fedcba9876543210abcdef10'
    required: true
  source-read-token:
    description: 'The GitHub personal access token to read from the source repository. Ex: foo_abcdefghi123456789abcdefghi123456789'
    required: true
  target-repository:
    description: 'The target repository to which to cherry pick. Ex: myOrg/my-target-repo'
    required: true
  target-branch:
    description: 'The target branch on which to cherry pick the commit. Ex: main'
    required: true
  target-read-write-token:
    description: 'The GitHub personal access token to read and write to the target repository. Ex: foo_abcdefghi123456789abcdefghi123456789'
    required: true
runs:
  using: 'composite'
  steps:
    - name: get friendly name
      id: friendly-name
      shell: bash
      run: |
        substr=$(echo ${{ inputs.commit-sha }} | cut -c1-7)
        echo ::set-output name=substr::$substr

    - name: cherry-pick sha from source to target
      shell: bash
      run: |
        echo Starting clone ... &&
        git clone https://${{ inputs.target-read-write-token }}@github.com/${{ inputs.target-repository }}.git ${{ inputs.commit-sha }} &&
        echo Clone finished, starting cd ... &&
        cd ${{ inputs.commit-sha }} &&
        echo cd finished, starting checkout ... &&
        git checkout ${{ inputs.target-branch }} &&
        echo checkout finished, starting branch creation &&
        git checkout -b boilerbot/${{ steps.friendly-name.outputs.substr }} &&
        echo branch creation finished, starting fetch &&
        git fetch https://${{ inputs.source-read-token }}@github.com/${{ inputs.source-repository }}.git &&
        echo fetch completed, starting cherry pick &&
        git cherry-pick ${{ inputs.commit-sha }} &&
        echo cherry pick completed, starting push &&
        git push origin boilerbot/${{ steps.friendly-name.outputs.substr }} &&
        echo push completed

    - name: create pull request
      shell: bash
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ inputs.target-read-write-token }}" \
        https://api.github.com/repos/${{ inputs.target-repository }}/pulls \
        -d '{ "title": "boilerbot cherry-pick ${{ steps.friendly-name.outputs.substr }}", "head": "boilerbot/${{ steps.friendly-name.outputs.substr }}", "base", "${{ inputs.target-branch }}" }'